// <auto-generated />
namespace LTQL_1721050355.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class heheheehe : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(heheheehe));
        
        string IMigrationMetadata.Id
        {
            get { return "202112210625026_heheheehe"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
